[general]
import = [
    "~/.alacritty.theme.toml",
]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
style = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "P"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "N"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Comma"
mods = "Shift|Control|Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Period"
mods = "Shift|Control|Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mode = "Alt"

[[keyboard.bindings]]
command = {program = "sh", args = ["-c", "~/.config/alacritty/theme-toggle.sh"]}
key = "t"
mods = "Control|Alt"

[scrolling]
history = 10000
multiplier = 3

[window]
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true
opacity = 1.0 # 0.91

[terminal]
osc52 = "CopyPaste"

[selection]
save_to_clipboard = true

[mouse]
# TODO
#hide_when_typing = true
bindings = [
#{ mouse = "Middle", mods = "Shift", action = "PasteSelection"  },
#{ mouse = "Right",  mods = "Shift", action = "Paste"  },
#{ mouse = "Middle",  action = "None"  },
#{ mouse = "Right",  action = "None"  },
]
