[bell]
color = "#023210"

[colors.cursor]
cursor = "#30ffff"
text = "#000000"

[colors.normal]
black = "#05141a"
red = "#ca0a2a"
green = "#0ab230"
yellow = "#b0b02a"
blue = "#1444c2"
magenta = "#c020df"
cyan = "#30bce2"
white = "#aacfda"

[colors.bright]
black = "#1a3248"
red = "#ff1816"
green = "#1fff2a"
yellow = "#ffff24"
blue = "#1294ff"
magenta = "#ff2bff"
cyan = "#3affff"
white = "#ffffff"

[colors.primary]
background = "#000108"
bright_foreground = "#02aacd" # ??
dim_foreground = "#020a0f" # ??
foreground = "#3072ff"

[colors.search.matches]
background = "#002412"
foreground = "#0256ce"

[colors.selection]
background = "#009a70"
